import random # VARIABLE ALEATORIA.

def reach_random_word(): # DEFINIMOS PALABRAS ALEATORIAS.
    words = ["ball", "cat", "dog", "fish", "software"] # MEDIANTE UN DICCIONARIO DE PALABRAS, SE DEFINEN MANUALMENTE AL MOMENTO DE DELETREAR CUALQUIER PALABRA AL AZAR.
    random_word = random.choice(words) # PALABRAS ALEATORIAS INGRESADAS AL DICCIONARIO DE PALABRAS.
    return random_word # RETORNA UNA PALABRA ALEATORIA.